proto: Add example.cpp to get working JSON serialization
In a separate branch where I tried to handle Any in Go, I got [1]:

  go run ./example.go
  go/config.pb.go:26:8: cannot find package "google/protobuf" in any of:
          /usr/lib/go/src/google/protobuf (from $GOROOT)
          /home/wking/.local/lib/go/src/google/protobuf (from $GOPATH)
  Makefile:31: recipe for target 'example' failed

This commit switches the main example to C++, because it's protobuf's
implementation language, so new features like Any support tend to land
there first.

The example tries to round-trip source JSON into a protobuf message
and back.  It does that by reading from config.json (I've skipped
runtime.json for now) into a message, and then writing JSON serialized
from that message to stdout.  Attributes in the input JSON file that
aren't represented in the protobuf message structure seem to be
silently dropped (which makes forward compatibility somewhat easier,
but explicit validation somewhat harder ;).

The docs for this sort of thing seem sparse (although there is a stale
C++ Any example here [2]).  The source skeleton [3] and Makefile rule
[4] are based on the protobuf examples.  kTypeUrlPrefix [5],
GetTypeUrl [6], the resolver handling [7,8], and the basic to/from
JSON conversion [9].

The commented-out LinuxUser section was how I figured out what to put
in the process.user block of config.json.  The bits of that that
weren't in [10], I figured out just by reading proto/cpp/config.pb.h.

The Makefile rule should likely be using:

   $(filter %.cc, $(CPP_FILES))

but my more restrictive filter removes runtime_config.pb.cc to avoid:

  $ make example_cpp
  c++ example.cc ./cpp/config.pb.cc ./cpp/runtime_config.pb.cc -o example_cpp $(pkg-config --cflags --libs protobuf) -I ./cpp
  ./cpp/runtime_config.pb.h:647:30: error: expected unqualified-id before numeric constant
     const ::oci::LinuxRuntime& linux() const;
                                ^
  ...

[1]: https://github.com/vbatts/specs/pull/2
[2]: https://developers.google.com/protocol-buffers/docs/proto3#any
     Although it recommends:
       status.add_details()->PackFrom(details);
     And the actual usage would be:
       status.mutable_details()->PackFrom(details);
     See [10].
[3]: https://github.com/google/protobuf/blob/v3.0.0-beta-1/examples/add_person.cc
[4]: https://github.com/google/protobuf/blob/v3.0.0-beta-1/examples/Makefile#L24-L26
[5]: https://github.com/google/protobuf/blob/v3.0.0-beta-1/src/google/protobuf/util/json_util_test.cc#L52
[6]: https://github.com/google/protobuf/blob/v3.0.0-beta-1/src/google/protobuf/util/json_util_test.cc#L54-L56
[7]: https://github.com/google/protobuf/blob/v3.0.0-beta-1/src/google/protobuf/util/json_util_test.cc#L66-L67
[8]: https://github.com/google/protobuf/blob/v3.0.0-beta-1/src/google/protobuf/util/json_util_test.cc#L85
[9]: https://github.com/google/protobuf/blob/v3.0.0-beta-1/src/google/protobuf/util/json_util_test.cc#L70-L83
[10]: https://github.com/google/protobuf/blob/v3.0.0-beta-1/src/google/protobuf/any_test.cc#L42

Signed-off-by: W. Trevor King <wking@tremily.us>